CREATE TABLE IF NOT EXISTS public.fixed_expense_payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  fixed_item_created_at bigint NOT NULL,
  due_date date NOT NULL,
  paid_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fixed_expense_payments_user_item_due_unique
    UNIQUE (user_id, fixed_item_created_at, due_date)
);

CREATE INDEX IF NOT EXISTS fixed_expense_payments_user_due_idx
  ON public.fixed_expense_payments (user_id, due_date);

ALTER TABLE public.fixed_expense_payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY fixed_expense_payments_owner_select
  ON public.fixed_expense_payments
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY fixed_expense_payments_owner_insert
  ON public.fixed_expense_payments
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY fixed_expense_payments_owner_delete
  ON public.fixed_expense_payments
  FOR DELETE
  USING (auth.uid() = user_id);
