name: CI (PR) & CD (main)

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: soomtong-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  # CI: PR 검증 단계 (빌드만)
  ci-build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20.x }
      - uses: pnpm/action-setup@v2
        with: { version: 10 }
      - uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-
      - name: Install & Build
        run: |
          pnpm install --frozen-lockfile
          pnpm build

  # CD: main push 시 배포 단계
  cd-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build & Push Docker image
        env:
          REPO: ${{ github.repository }}
        run: |
          IMAGE_RAW="ghcr.io/${REPO}:latest"
          IMAGE=$(echo "$IMAGE_RAW" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Upload deploy assets to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml,Caddyfile,deploy.sh"
          target: "/home/ubuntu/soomtong/"
          overwrite: true

      - name: Run deploy.sh on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euo pipefail
            cd /home/ubuntu/soomtong
            command -v dos2unix >/dev/null 2>&1 && dos2unix deploy.sh || true
            chmod +x deploy.sh
            ./deploy.sh
